name: aoc_2021
description: Advent of Code 2021.
version: 1.0.0
homepage: https://marcelo-mds.dev

environment:
  sdk: '>=2.14.4 <3.0.0'

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
