name: dw_backend
description: Backend with Shelf.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.16.1 <3.0.0'

dev_dependencies:
  lints: ^1.0.0

dependencies:
  dart_jsonwebtoken: ^2.4.1
  mysql1: ^0.19.2
  shelf: ^1.3.0
  shelf_router: ^1.1.2
